server:
  port: 10031
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:127.0.0.1:3306}/${MYSQL_DATABASE:hibiscus-mgt}?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&useUnicode=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari-pool
      connection-timeout: 60000
      minimum-idle: 20
      maximum-pool-size: 500
      max-lifetime: 1800000
      validation-timeout: 3000
      idle-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
eureka:
  instance:
    hostname: 192.168.31.208
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: ${app.eureka.client.url}
# 日志配置
logging:
  file:
    path: logs/
    name: ${spring.application.name}.log
app:
  eureka:
    client:
      port: 10001
      hostname: localhost
      url: http://${app.eureka.client.hostname}:${app.eureka.client.port}/eureka/
